### PR TITLE
chore: update Tera templating library website URL

### LINKED ISSUE #167: Tera link needs update: https://keats.github.io/tera/
New URL: <https://keats.github.io/tera/>

[The current link](https://tera.netlify.app/) appears outdated:

image

### PR DESCRIPTION
**Pull request by LeoniePhiline**
Fixes #167

### CODE REVIEW

**Comment by flosse** [comment]
@LeoniePhiline thank's for your contribution. Unfortunately, this patch is overwritten as soon as `cargo build` is executed again.
Would you mind to adjust the link in the source?
https://github.com/flosse/rust-web-framework-comparison/blob/ae3f9ba84f3666b90de60689f7327db0e75ecdbc/data.toml#L479

**Comment by LeoniePhiline** [comment]
Oh dang, I had been in a rush 🤦🏼‍♀️

I'll prepare a new PR, editing the data.toml once I find the time.

**Comment by LeoniePhiline** [comment]
PTAL :)

**Comment by flosse** [comment]
thx!

**Pull request merged**
